language: python
python:
  - 2.6
  - 2.7
services:
    - couchdb
install: make install
script:  make tests
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
notifications:
    irc:
        channels:
            - "irc.freenode.org#daybed"
        on_success: change
