language: python
python: 2.7
services:
    - couchdb
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=flake8
script: tox -e $TOX_ENV
install:
    - pip install tox
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
