language: python
python:
  - 2.6
  - 2.7
  - 3.2
services:
    - couchdb
install: make install
script:  make tests
notifications:
    irc:
        channels:
            - "irc.freenode.org#daybed"
        on_success: change
